--employees에서 전체내용 조회
SELECT * 
FROM EMPLOYEES e;

--first name, last name, job_id 조회
SELECT FIRST_name, LAST_name, job_id
FROM EMPLOYEES e;

--사원번호가 176인 사람의 LAST NAME 과 DEPARTMENT_ID 조회
SELECT LAST_NAME , DEPARTMENT_ID
FROM EMPLOYEES e
WHERE EMPLOYEE_ID = 176;
--연봉이 12000이상 되는 직원들의 LAST_NAME과 SALARY 조회
SELECT LAST_NAME , SALARY
FROM EMPLOYEES e
WHERE SALARY> = 12000;
--연봉이 5000에서 12000의 범위 이외인 사람들의 LAST_NAME과 SALARY 조회
SELECT LAST_NAME , SALARY
FROM EMPLOYEES e
WHERE SALARY< 5000 OR SALARY> 12000;

--LAST NAME에 u 가 포함되는 사원들의 사번, last_name 조회
SELECT EMPLOYEE_ID, LAST_NAME
FROM EMPLOYEES e
WHERE LAST_NAME LIKE '%u%';


--LAST_NAME에 a 혹은 e 글자가 들어있는 사원들의 사번, last_name 조회 후 last_name 오름차순 조회
SELECT EMPLOYEE_ID, LAST_NAME 
FROM EMPLOYEES e
WHERE LAST_NAME LIKE '___a%';

--LAST_NAME에 a와 e 글자가 들어있는 사원들의 사번, last_name 조회 후 last_name 오름차순 조회

SELECT EMPLOYEE_ID, LAST_NAME 
FROM EMPLOYEES e
WHERE LAST_NAME LIKE '%a%' OR LAST_NAME LIKE '%e%'
ORDER BY LAST_NAME ASC;

--LAST NAME 에 a와 e 글자가 들어있는 사원들의 사번,last name 조히 후 last name 오름차순 조회
--davies,devias

SELECT EMPLOYEE_ID, LAST_NAME 
FROM EMPLOYEES e
WHERE LAST_NAME LIKE '%a%e%' OR LAST_NAME LIKE '%e%'
ORDER BY LAST_NAME ASC;

--
SELECT *
FROM EMPLOYEES e ;

--매니저가 없는 사람들의 LAST_NAME, JOB_ID 조회
SELECT LAST_NAME, JOB_ID
FROM EMPLOYEES e 
WHERE MANAGER_ID IS NULL;

--ST_CLERK 인 JOB_ID를 가진 사원이 없는 부서 ID 조회(단, 부서번호가 NULL인 사원 제외)
SELECT DISTINCT DEPARTMENT_ID 
FROM EMPLOYEES e 
WHERE JOB_ID != 'ST CLERK' AND DEPARTMENT_ID IS NOT NULL;

--COMMISSION_PCT가 NULL이 아닌 사원들 중에서 COMMISSION = SALARY * COMMISSION_PCT
--를 구하여 EMPLOYEE_ID, FIRST_NAME, JOB_ID를 조회
SELECT DEPARTMENT_ID, FIRST_NAME, JOB_ID, SALARY * COMMISSION_PCT AS COMMISSION
FROM EMPLOYEES e
WHERE COMMISSION_PCT IS NOT NULL;

--NULL * 숫자= NULL
SELECT DEPARTMENT_ID, FIRST_NAME, JOB_ID,SALARY, SALARY * COMMISSION_PCT AS COMMISSION
FROM EMPLOYEES e

--FIRST_NAME 이 'Curtis'인 사원의 first_name, last_name,email, phon_numer, job_id 를
--조회한다. 단 job_id 결과는 소문자로 출력한다
SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, lOWER(JOB_ID)
FROM EMPLOYEES e
WHERE FIRST_NAME = 'Curtis';

--부서번호가 60,70,80,90 인 사원들의 employee_id,first_name,hire_date,job_id 조회
--단, job_id가 IT_PROG인 사원의 경우 프로그래머로 변경하여 출력한다.
SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE, REPLACE (JOB_ID, 'IT_PROG', '프로그래머')
FROM EMPLOYEES e
WHERE DEPARTMENT_ID IN (60,70,80,90);
--JOB_ID RK AD_PRES, PU_CLERK 인 사원들의 employee_id,first_name,job_id 조회
--단, 사원명은 FIRST_NAME과 LAST_NAME을 공백을 포함하여 연결
--'ABC', 'DEF' => 'ABC DEF'
SELECT EMPLOYEE_ID, FIRST_NAME||' ' ||LAST_NAME AS NAME, JOB_ID
FROM EMPLOYEES e
WHERE JOB_ID IN ('AD_PRES', 'PU_CLERK');

--실습 4: 부서 80의 각 사원에 대해 적용 가능한 세율을 표시하시오

SELECT LAST_NAME,
SALARY, 
CASE trunc(salary/2000,0)
    WHEN 0 THEN '0%'
    WHEN 1 THEN '9%'
    WHEN 2 THEN '20%'
    WHEN 3 THEN '30%'
    WHEN 4 THEN '40%'
    WHEN 5 THEN '42%'
    WHEN 6 THEN '44%'
    ELSE '45%'
END AS TAX_RATE
FROM EMPLOYEES e 
WHERE DEPARTMENT_ID = 80;

--최대연봉 - 최소연봉 차이 조회

--매니저로 근무하는 사원들의 총 수 조회(매니저번호 중복 제거)


SELECT MAX(SALARY) - MIN(SALARY)
FROM EMPLOYEES e;

SELECT COUNT(DISTINCT MANAGER_ID)
FROM EMPLOYEES e;

--부서별 직원 수 구하기(부서번호의 오름차순 출력)
SELECT DEPARTMENT_ID, COUNT(EMPLOYEE_ID)
FROM EMPLOYEES e
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID; 
--부서별 평균 급여
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES e 
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;
--동일한 직무(job_id)를 가진 사원들의 총 수 조회

SELECT DEPARTMENT_ID, COUNT(EMPLOYEE_ID)
FROM EMPLOYEES e
GROUP BY DEPTNO;

--매니저가 관리하는 사원들 중에서 최소급여 조회
--매니저가 관리하는 사원들 중에서 최소급여가 6000 미만인 최소급여는 제외
--매니저가 없는 사원 제외
SELECT MANAGER_ID, MIN(SALARY)
FROM EMPLOYEES e
WHERE MANAGER_ID IS NOT NULL 
GROUP BY MANAGER_ID HAVING MIN(SALARY) >=6000
ORDER BY MANAGER_ID; 

-- 자신이 담당 매니저의 고용일보다 빠른 입사자 찾기
SELECT
	e.EMPLOYEE_ID AS 내사원번호,
	e.hire_date AS 내입사일,
	e.manager_id AS 매니저번호,
	e2.HIRE_DATE AS 매니저입사일
FROM
	EMPLOYEES e
JOIN EMPLOYEES e2 ON
	e.manager_id = E2.EMPLOYEE_ID AND e.hire_date<e2.hire_date;

--도시 이름이 T로 시작하는 지역에 사는 사원들의 사번,last_name, 부서번호 조회
--(도시명은 Locations 테이블에)
SELECT
	*
FROM
	EMPLOYEES e
JOIN DEPARTMENTS d ON
	e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN LOCATIONS l ON
	d.LOCATION_ID = l.LOCATION_ID
WHERE
	l.CITY LIKE '1%';

--위치 아이디가 1700인 사원들의 last_name, 부서번호, 연봉 조회
SELECT e.LAST_NAME, e.DEPARTMENTS, e.SALARY 
FROM EMPLOYEES e JOIN DEPARTMENTS = d.DEPARTMENT_ID
WHERE d.LOCATION_ID = 1700;

--부서명, 위치ID, 각 부서별 사원 수, 각 부서별 평균 연봉 조회
--평균 연봉은 소수점 2자리까지만 표현
SELECT d.DEPARTMENT_NAME,d.LOCATION ,DISTINCT , AVG(SALARY)
FROM EMPLOYEES e 

--Excutive 부서에 근무하는 사원들의 부서번호, last_name, job_id 조회
SELECT
	d.DEPARTMENT_ID,
	e.LAST_NAME,
	e.JOB_ID
FROM
	EMPLOYEES e
JOIN DEPARTMENTS d ON
	e.DEPARTMENT_ID = d.DEPARTMENT_ID
	AND d.DEPARTMENT_NAME = 'Excutive';

--각 사원별 소속 부서에서 자신보다 늦게 고용되었으나 많은 연봉을 받는 사원이 존재하는
--사원들의 이름 조회(이름은 first_name과 last_name을 결합하여 하나로 나오게 하기)
--부서번호, 결합된 이름, salary, hire_date 출력
SELECT
    DISTINCT e.department_id AS 부서번호,
	e.FIRST_NAME || ' ' || e.last_name AS "내이름",
	e.SALARY AS 내급여,
	e.hire_date AS 내입사일
FROM
	EMPLOYEES e
JOIN EMPLOYEES e2 ON
	e.DEPARTMENT_ID = E2.DEPARTMENT_ID
	AND e.salary <E2.SALARY AND e.hire_date<E2.HIRE_DATE;

--LAST_NAME에 u가 포함되는 사원들과 동일 부서에 근무하는 사원들의 사번 및 last_name 조회
--사번 오름차순

SELECT e.EMPLOYEE_ID,e.LAST_NAME
FROM EMPLOYEES e 
WHERE e.DEPARTMENT_ID IN (SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES e
WHERE LAST_NAME LIKE '%U%')
ORDER BY e.EMPLOYEE_ID;


SELECT DISTINCT  DEPARTMENT_ID
FROM EMPLOYEES e 
WHERE LAST_NAME LIKE '%u%';


--기존의 직업을 여전히 가지고 있는 사원들의 사번 및 job_id 조회
--emplyees, job_history 이용

SELECT e.EMPLOYEE_ID, e.JOB_ID 
FROM EMPLOYEES e 
WHERE (e.EMPLOYEE_ID, e.JOB_ID) IN (SELECT jh.employee_id, jh.job_id FROM JOB_HISTORY jh);


--SELECT 서브쿼리
--각 직무별 연봉 총합 및 각 부서별 연봉 총합 조회
--JOB_ID, 부서별연봉총ㅎ바, 전체총합

SELECT JOB_ID, (SELECT SUM(SALARY) FROM EMPLOYEES e2 WHERE DEPARTMENT_ID=10 AND E.JOB_ID=E2.JOB_ID) AS DEPT10,
 (SELECT SUM(SALARY) FROM EMPLOYEES e2 WHERE DEPARTMENT_ID=20 AND E.JOB_ID=E2.JOB_ID) AS DEPT20,
 (SELECT SUM(SALARY) FROM EMPLOYEES e2 WHERE DEPARTMENT_ID=30 AND E.JOB_ID=E2.JOB_ID) AS DEPT30,
 (SELECT SUM(SALARY) FROM EMPLOYEES e2 WHERE DEPARTMENT_ID=40 AND E.JOB_ID=E2.JOB_ID) AS DEPT40,
 (SELECT SUM(SALARY) FROM EMPLOYEES e2 WHERE DEPARTMENT_ID=50 AND E.JOB_ID=E2.JOB_ID) AS DEPT50,
 (SELECT SUM(SALARY) FROM EMPLOYEES e2 WHERE DEPARTMENT_ID=60 AND E.JOB_ID=E2.JOB_ID) AS DEPT60,
 (SELECT SUM(SALARY) FROM EMPLOYEES e2 WHERE DEPARTMENT_ID=70 AND E.JOB_ID=E2.JOB_ID) AS DEPT70,
 (SELECT SUM(SALARY) FROM EMPLOYEES e2 WHERE DEPARTMENT_ID=80 AND E.JOB_ID=E2.JOB_ID) AS DEPT80,
 (SELECT SUM(SALARY) FROM EMPLOYEES e2 WHERE DEPARTMENT_ID=90 AND E.JOB_ID=E2.JOB_ID) AS DEPT90,
 (SELECT SUM(SALARY) FROM EMPLOYEES e2 WHERE DEPARTMENT_ID=100 AND E.JOB_ID=E2.JOB_ID) AS DEPT100,
 (SELECT SUM(SALARY) FROM EMPLOYEES e2 WHERE DEPARTMENT_ID=110 AND E.JOB_ID=E2.JOB_ID) AS DEPT110,
FROM EMPLOYEES e 
GROUP BY JOB_ID 
ORDER BY JOB_ID;

--JOB_ID 가 SA_MAN 인 사원들의 최대 연봉보다 높게 받는 사원들의 LAST_NAME, JOB_ID, SALARY 조회
SELECT LAST_NAME, JOB_ID, SALARY
FROM EMPLOYEES e
WHERE SALARY > (SELECT MAX(SALARY)
FROM EMPLOYEES e
WHERE JOB_ID = 'SA_MAN');

--커미션을 버는 사원들의 부서와 연봉이 동일한 사원들의 LAST_NAME, 부서번호, 연봉 조회

SELECT
	LAST_NAME DEPARTMENT_ID,
	SALARY
FROM
	EMPLOYEES e
WHERE
	DEPARTMENT_ID , SALARY
(
	SELECT
		DEPARTMENT_ID,
		SALARY
	FROM
		EMPLOYEES e
	WHERE
		COMMISSION_PCT IS NOT NULL);



--회사 전체 평균 연봉보다 더 많이 버는 사원들 중 LAST_NAME에 u가 있는 사원들이 근무하는 부서에서 근무하는
--사원들의 사번, LAST_NAME, 연봉 조회
SELECT
	EMPLOYEE_ID,
	LAST_NAME,
	SALARY
FROM
	EMPLOYEES e
WHERE
	DEPARTMENT_ID IN
(
	SELECT
		DISTINCT DEPARTMENT_ID
	FROM
		EMPLOYEES e
	WHERE
		SALARY > (
		SELECT
			AVG(E.SALARY)
		FROM
			EMPLOYEES e)
		AND LAST_NAME LIKE '%u%');
	
--각 부서별 평균 연봉보다 더  받는 동일 부서 근무사원들의 LAST_NAME, 부서번호, 연봉 및 해당 부서의 평균 연봉 조회
--부서별 연봉을 기준으로 정렬

SELECT
	E1.LAST_NAME, E1.DEPARTMENT_ID, E1.SALARY, E2.DEPT_SAL_AVG
FROM
    EMPLOYEES E1,
	(
	SELECT
		DEPARTMENT_ID , 
		AVG(SALARY) AS DEPT_SAL_AVG
	FROM
		EMPLOYEES e
	GROUP BY
		DEPARTMENT_ID) E2
	WHERE 
	   E1.DEPARTMENT_ID = E2.DEPARTMENT_ID AND E1.SALARY > E2.DEPT_SAL_AVG
    ORDER BY E1.DEPARTMENT_ID;


--last_name이 Davies 인 사람보다 후에 고용된 사원들의 last_name, hire_date 조회
SELECT LAST_NAME , HIRE_DATE
FROM EMPLOYEES e 
WHERE HIRE_DATE>(SELECT HIRE_DATE 
FROM EMPLOYEES e 
WHERE LAST_NAME = 'Davies')

--last_name 이 king인 사원을 매니저로 두고 있는 모든 사원들의 last_name, salary 조회
SELECT LAST_NAME, HIRE_DATE 
FROM EMPLOYEES e
WHERE MANAGER_ID IN (SELECT EMPLOYEE_ID
FROM EMPLOYEES e
WHERE LAST_NAME ='King');


--last_name 이 kochhar인 사원과 동일한 연봉 및 커미션을 버는 사원들의 last_name, 부서번호, salary 조회
--kochhar 은 제외한다
SELECT
	LAST_NAME,
	DEPARTMENT_ID,
	SALARY
FROM
	EMPLOYEES e
WHERE
	(SALARY,
	NVL(COMMISSION_PCT, 0)) IN (
	SELECT
		SALARY,
		COMMISSION_PCT
	FROM
		EMPLOYEES e
	WHERE
		LAST_NAME = 'Kochhar');

--부서가 위치한 국가 ID, 이름 조회
--COUNTRIES 테이블과 locations, departments 이용
SELECT
	COUNTRY_ID ,
	COUNTRY_NAME
FROM
	COUNTRIES c
WHERE
	COUNTRY_ID IN (
	SELECT
		L.COUNTRY_ID
	FROM
		DEPARTMENTS) D	
	WHERE
		L.LOCATION_ID = D.LOCATION_ID;
--총 사원 수 및 2013,2014,2015,2016년도 별 고용된 사원들의 총 수를 조회한다
--SELECT COUNT(EMPLOYEE_ID) FROM EMPLOYEES WHERE LIKE '13%';
--SELECT COUNT(EMPLOYEE_ID) FROM 	
SELECT
	DISTINCT (
	SELECT
		COUNT(EMPLOYEE_ID)
	FROM
		EMPLOYEES e2) AS "총 사원수" ,
FROM
	EMPLOYEES
WHERE
	TO_CHAR(HIRE_DATE, 'YY')= '14')
AS "2014",
	(
	SELECT
		COUNT(EMPLOYEE_ID)
	FROM
		EMPLOYEES
	WHERE
		TO_CHAR(HIRE_DATE, 'YY') = '15')
AS "2015",
	(
	SELECT
		COUNT(EMPLOYEE_ID)
	FROM
		EMPLOYEES
	WHERE
		TO_CHAR(HIRE_DATE, 'YY')= '16')
AS "2016"
FROM
	EMPLOYEES e;

--위치 ID가 1700인 사원들의 연봉과 커미션을 추출한 뒤, 추출된 사원들의 연봉과 커미션이 동일한 사원번호 조회
-- 사원번호, 이름(first+last 결합), 부서번호, 급여 출력

SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME AS NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES e 
WHERE (SALARY, NVL(COMMISSION_PCT,0)) IN 
(SELECT SALARY, NVL(COMMISSION_PCT,0)
FROM EMPLOYEES e 		
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID
FROM DEPARTMENTS d 
WHERE D.LOCATION_ID = 1700));




	
